#!/bin/bash

# This is a modified bash script provided in the ethical hacking and pen. testing course SEC-335.

read -e -p "Enter the host prefix (target) file:" HOSTFILE

read -e -p "Enter the port (tcp/udp):" PORT

echo "ip,port"
for host in $(cat $HOSTFILE); do
    timeout .1 bash -c "echo >/dev/tcp/$host/$PORT" 2>/dev/null &&
      echo "$host,$port"
  done
done
