#!/bin/bash

# This is a modified bash script provided in the ethical hacking and pen. testing course SEC-335.
# Finsihed product produced with help from Tom Claflin

prefix=$1
port=$2

echo "ip,port"
for i in $(seq 1 254); do
    timeout .1 bash -c "echo >/dev/tcp/$prefix.$i/$port" 2>/dev/null &&
      echo "$prefix.$i,$port"
done
